services:
  App\Controller\Command\KafkaCommandHandler:
    arguments:
      - '@monolog.logger.messenger'

  App\Controller\Command\RabbitCommandHandler:
    arguments:
      - '@monolog.logger.messenger'
